Repository MailRuChamps/miniaicups, pull requests merged in 2019-07, with the labels that each got.

#273 Add "derive" feature to serde crate
  paperio/dockers/rust/Cargo.toml
Labels: enhancement, in progress

#263 Scala: added de-facto standard json library
  paperio/dockers/scala/build.sbt
Labels: enhancement, in progress

#258 Фикс путей спрайтов для запуска localrunner с любым cwd
  paperio/local_runner/helpers.py
Labels: bug, in progress

#264 любое начальное направление движения
  paperio/local_runner/game_objects/player.py
Labels: bug, in progress

#244 Rust: edition = "2018"
  paperio/dockers/rust/Cargo.toml
Labels: in progress

#285 Update kotlin version
  paperio/dockers/kotlin/build.gradle
Labels: help wanted, in progress
